### ISSUE TITLE
[feature] nested variables

### ISSUE THREAD

**Issue by perrymanuk** [hashicorp/levant#233]
**Description**

Would like the ability to do something like [[ .[[ .var1 ]].var2 ]] so that the variables themselves can be templated. Reasoning is if we have different settings across different datacenters or regions for a deployment it would allow us to keep one variable file with all of the variables in it rather than having to keep multiple files for each region/dc for the same application.

**Comment by jrasell** [comment]
thanks for raising the issue @perrymanuk. could you give a couple of examples of the variables that would be substituted so I can better understand?

**Comment by dropje86** [comment]
I wonder if this is not already solvable the way it is.
Option 1:
Have multiple var-files. 1 file with “shared” variables used in all regions, 1 specific with region vars. Use a variable in your CI/CD with a region selection: `-var-file=${REGION}.yaml`

Option 2:
Override these specific vars by using -var “${REGION}_count=2”.

**Comment by jrasell** [comment]
Thanks @perrymanuk for the detail. I think the two suggestions @dropje86 gives would be suitable for this use case and I would be curious if that works for you? The example and feature you're describing would require significant templating changes, and may even require running two templating actions across the file, first to render the variable concatenation, and the second to render the variables themselves.

**Comment by perrymanuk** [comment]
@dropje86 This is how I am currently handling it however with ~400 of these applications and 4 regions its a bit cumbersome to maintain a separate region file for each application as I end up with 1600 files in my build repo that way.

**Comment by dropje86** [comment]
Hmm yeah that’s a pretty substantial setup. So what if you do exactly like you say; split up var-file per region and prefix each var specific to your app with appname_count. Wouldn’t that yield exactly the same result as nested variables? So basically divide your var-file in app sections.

**Comment by perrymanuk** [comment]
Maybe I am not following exactly, but wouldn't I still need a var per region per app with what you are describing? Also maybe I should say that it isn't just the count that changes. I also have some metadata for autoscaling, and a few other variables that vary per region.

**Comment by dropje86** [comment]
So, it kind of depends on the amount of unique variables you have per application. If you have a lot of common vars you could have (similar to hiera) a hierarchy. Smth like: base.yaml containing variables like:

`base.yaml`:
```yaml
---
myapp_count: 3
myapp_meta_whatever: valueHere
```
If you need region specifics/overrides you do the same thing. Example:

`eu-west-2.yaml`:
```yaml
---
myapp_count: 1
```
Execute levant with: `levant deploy -var-file base.yaml -var-file ${REGION}.yaml job.nomad`
It's a bit of a trade-off. Either you have a file per service per region, or a big file and use unique variable names to distinguish between services.

**Comment by perrymanuk** [comment]
Ah, I think I see our confusion. The variables are different per region too so app1 and app2 will have different settings for region1 and app1 will have different settings in region1 and region2.

**Comment by perrymanuk** [comment]
@stevenscg interesting idea, but will levant pull consul values from each region its deploying to, or just from the one in which you run it?

**Comment by stevenscg** [comment]
@perrymanuk Hard to say for sure without knowing more about your topology.

Example: If you run a consul cluster in each region or dc (loose terms here since consul and nomad vary slightly), levant would first connect to consul in dc1 and pull the vars for the application and then connect to nomad in dc1 to submit the job.

If you are using federation between regions or dcs, you'll probably have to make that connection to a specific consul cluster to get the vars you need for that region/dc.

A completely different way to approach the task count issue is to deploy jobs with a "minimum" count and then use the `scale-in` or `scale-out` commands in levant to set the count that you want. We actually do exactly this these days. `levant` will maintain the task counts that are currently deployed in the cluster unless you use the `force-count` option.

I initially thought about addressing the task counts issue, but found that we size the jobs roughly at the beginning with a few quick changes and then rarely have to touch it again. For really dynamic workloads, we've considered [replicator](https://github.com/elsevier-core-engineering/replicator) but have yet to pull the trigger.

I also like @dropje86's multiple var file solution and may use it in the future. It wasn't an option when we first rolled out levant.

**Comment by angrycub** [comment]
I know that this issue is rather old, but I wanted to show one way to solve the original example using the `index` function.

Given the example yaml and a var set on the command line, you can get a specific set of values using the index template function.

levant-233.yaml
```yaml
region1:
  count: 2
region2:
  count: 4
region3:
  count: 6
```

levant-233.nomad
```
[[- with index . .region ]][[ .count ]][[ end ]]
```

You can then use a `-var` flag to pass in a region name to be used as an index.

```
levant render -var-file=levant-233.yaml -var region="region1" levant-233.nomad  2>/dev/null 
2
levant render -var-file=levant-233.yaml -var region="region2" levant-233.nomad  2>/dev/null
4
levant render -var-file=levant-233.yaml -var region="region3" levant-233.nomad  2>/dev/null
6
```

You could also store the region specific configuration into a variable, which might be useful in cases where there are more child settings 

```
[[ $REGION := index . .region -]]
[[ $REGION.count ]]
```
